# Generated by Django 5.2.4 on 2025-12-25 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_post_photo_url_post_image'),
        ('stores', '0009_store_popular_menu_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='store',
            field=models.ForeignKey(blank=True, help_text='빵집 추천 카테고리일 경우 연결된 빵집', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='stores.store'),
        ),
    ]
